name = "WCS"
uuid = "15f3aee2-9e10-537f-b834-a6fb8bdb944d"
version = "0.6.3"

[workspace]
projects = ["test", "docs"]

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
WCS_jll = "550c8279-ae0e-5d1b-948f-937f2608a23e"

[compat]
ConstructionBase = "1"
WCS_jll = "7"
julia = "1.10"
